### ISSUE TITLE
Clean Install/Not VM - Where Is System Log Viewer In LM 22.1 Beta Cinnamon?

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22.1-beta#53]
LM 22.1 Beta Cinnamon.

Where is system log viewer?
I typed in the word: "log" in Start menu search and could not find it?

**Comment by clefebvre** [comment]
gnome-logs was removed since Mint 22 because it moved to libAdwaita and no longer supports themes.

Although it's nice to be to see logs, it's not something casual users do often, so It wasn't replaced.

**Comment by LinuxOnTheDesktop** [comment]
I think there is a problem here, because it means that two major log viewers display badly on Mint (or at least on Cinnamon. For, the Plasma system viewer ('ksystemlog') requires a lot of configuration in order to be themed properly. (0ne must use qt5ct and indeed run that program as root and in so doing weather a crash. I have documented this somewhere.)

**Comment by JesseLeePalser** [comment]
A system log viewer sometimes comes in handy...
...like when you are beta testing a new unstable Operating System.

GET RID OF UBUNTU ASAP!

**Comment by LinuxOnTheDesktop** [comment]
@JesseLeePalser 

Adding that radical and rather presumptive call will not do the request for an easily usable log viewer any good!
