### ISSUE TITLE
system: linux-image-6.8.0-49-generic is manually installed

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/mint22.1-beta#9]
linux-image-6.8.0-49-generic is manually installed, shouldn't be.

**Comment by clefebvre** [comment]
Postponed to 22.2.

The ISO does indeed ship with the kernel marked as manually installed but when the Update Manager finds a new kernel it also manually installs its new packages.

We have an item on the roadmap to turn kernel automatic removal ON by default. The reason we don't that yet is because we rely on autoremove which is clunky and dangerous system-wide.

We want to rewrite that feature to only remove kernels, and then turn it ON.

**Comment by contrarybaton60** [comment]
![image](https://github.com/user-attachments/assets/ade9fc28-8802-46d2-8771-a0753be5b66a)
one of the things I am worried though is what if someone (let's say a new user, not knowing what they're doing) decides to remove the kernel in the software manager? there's gonna be a bunch of support requests because of this I would imagine.
